### ISSUE TITLE
Adapt to Google Cloud Platform creating new instances when load increases

### ISSUE THREAD

**Issue by benbraou** [benbraou/ivy-status-api#8]
@jorgellose mentioned in https://github.com/angular/angular/issues/21706 that `is angular ivy ready` is not working for him. More precisely, I suppose he gets an empty page because the `ivy-status-api` is returning an empty response.

I checked google cloud platform logs and I see from time to time the message:
```
This request caused a new process to be started for your application, and thus caused your  application code to be loaded for the first time. This request may thus take longer and use more CPU than a typical request for your application.
```

When a new instance is create, `ivy-staus-api` returns an empty response for the 5 first minutes.

**Comment by benbraou** [comment]
@jorgellose please let me know if you still encounter any issues. Thanks!

**Comment by jorgellose** [comment]
@benbraou Solved
